### ISSUE TITLE
typo in nom activity record type values causing minting errors 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc_automation#147]
INFO:root:Getting new ID for ndmc:NomAnalysisActivity nmdc:1ffd38c0c3b54d70bd558f24341cc20c
Traceback (most recent call last):
  File "/Users/aclum/repos/nmdc_automation/nmdc_automation/re_iding/scripts/./re_id_tool.py", line 1152, in <module>
    cli(obj={})
  File "/Users/aclum/Library/Caches/pypoetry/virtualenvs/nmdc-automation-r_t-AIM_-py3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aclum/Library/Caches/pypoetry/virtualenvs/nmdc-automation-r_t-AIM_-py3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/aclum/Library/Caches/pypoetry/virtualenvs/nmdc-automation-r_t-AIM_-py3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aclum/Library/Caches/pypoetry/virtualenvs/nmdc-automation-r_t-AIM_-py3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aclum/Library/Caches/pypoetry/virtualenvs/nmdc-automation-r_t-AIM_-py3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/aclum/Library/Caches/pypoetry/virtualenvs/nmdc-automation-r_t-AIM_-py3.9/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/aclum/repos/nmdc_automation/nmdc_automation/re_iding/scripts/./re_id_tool.py", line 254, in update_study
    updated_omics_processing, updated_record_identifiers, updates = get_updates_for_metabolomics_or_nom(
  File "/Users/aclum/repos/nmdc_automation/nmdc_automation/re_iding/base.py", line 915, in get_updates_for_metabolomics_or_nom
    updated_activity_id = get_new_nmdc_id(activity, api_client, identifiers_map)
  File "/Users/aclum/repos/nmdc_automation/nmdc_automation/re_iding/base.py", line 632, in get_new_nmdc_id
    raise ValueError(f"Set name not found for {nmdc_object.type}")
ValueError: Set name not found for ndmc:NomAnalysisActivity

**Comment by aclum** [comment]
error says it is trying to mint with the wrong prefix, ndmc, instead of nmdc but i can't find where the typo is in the code.

**Comment by mbthornton-lbl** [comment]
@aclum  The `type` is incorrect for 50 records in `nom_analysis_activity_set`
example
```
{
    "_id" : ObjectId("649b0096daa6c19f56b27a8d"),
    "id" : "nmdc:a1453a2ae5bf4bcca2165b90b96d1082",
    "type" : "ndmc:NomAnalysisActivity",
    "ended_at_time" : "2021-12-10T11:30:44Z",
    "execution_resource" : "EMSL-RZR",
    "git_url" : "https://github.com/microbiomedata/enviroMS",
    "has_input" : [
        "emsl:output_570991"
    ],
    "has_calibration" : "false",
    "has_output" : [
        "nmdc:596ea737570fefcd00dc54b936cb0245"
    ],
    "started_at_time" : "2021-12-10T11:30:44Z",
    "used" : "21T_Agilent",
    "was_informed_by" : "emsl:570991"
}
```

**Comment by aclum** [comment]
Well this explains why I couldn't find a typo in your code :)
