### ISSUE TITLE
KeyError raised from api get_token when running re_id_tool process-records

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#29]
```shell
/Users/MBThornton/Library/Caches/pypoetry/virtualenvs/nmdc-automation-VEpwcKpc-py3.9/bin/Python /Users/MBThornton/Documents/code/nmdc_automation/nmdc_automation/re_iding/scripts/re_id_tool.py process-records --study_id nmdc:sty-11-8fb6t785 
/Users/MBThornton/Library/Caches/pypoetry/virtualenvs/nmdc-automation-VEpwcKpc-py3.9/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
2023-11-28 13:29:26,668 - root - INFO - Processing workflow records for study_id: nmdc:sty-11-8fb6t785
2023-11-28 13:29:26,668 - root - INFO - Running in dryrun mode
2023-11-28 13:29:26,669 - root - INFO - Running in dryrun mode
2023-11-28 13:29:26,669 - root - INFO - Using data_dir: /global/cfs/cdirs/m3408/results
2023-11-28 13:29:26,680 - root - INFO - Using db_infile: /Users/MBThornton/Documents/code/nmdc_automation/nmdc_automation/re_iding/scripts/data/dryrun_associated_record_dump.json
2023-11-28 13:29:26,681 - root - INFO - Read 1 records from db_infile
2023-11-28 13:29:26,681 - root - INFO - omics_processing_id: nmdc:omprc-11-bn8jcq58
Traceback (most recent call last):
  File "/Users/MBThornton/Documents/code/nmdc_automation/nmdc_automation/re_iding/scripts/re_id_tool.py", line 349, in <module>
    cli(obj={})
  File "/Users/MBThornton/Library/Caches/pypoetry/virtualenvs/nmdc-automation-VEpwcKpc-py3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/MBThornton/Library/Caches/pypoetry/virtualenvs/nmdc-automation-VEpwcKpc-py3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/MBThornton/Library/Caches/pypoetry/virtualenvs/nmdc-automation-VEpwcKpc-py3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/MBThornton/Library/Caches/pypoetry/virtualenvs/nmdc-automation-VEpwcKpc-py3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/MBThornton/Library/Caches/pypoetry/virtualenvs/nmdc-automation-VEpwcKpc-py3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/MBThornton/Library/Caches/pypoetry/virtualenvs/nmdc-automation-VEpwcKpc-py3.9/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/MBThornton/Documents/code/nmdc_automation/nmdc_automation/re_iding/scripts/re_id_tool.py", line 205, in process_records
    new_db = reid_tool.update_omics_processing_has_output(db_record, new_db)
  File "/Users/MBThornton/Documents/code/nmdc_automation/nmdc_automation/re_iding/base.py", line 124, in update_omics_processing_has_output
    new_do_id = self.api_client.minter("nmdc:DataObject")
  File "/Users/MBThornton/Documents/code/nmdc_automation/nmdc_automation/api/nmdcapi.py", line 59, in _get_token
    self.get_token()
  File "/Users/MBThornton/Documents/code/nmdc_automation/nmdc_automation/api/nmdcapi.py", line 79, in get_token
    expt = resp["expires"]
KeyError: 'expires'

Process finished with exit code 1

```

**Comment by Michal-Babins** [comment]
I was unable to replicate this error. I ran the dry run and was able to get a token using the nmdcapi library without changes.
