### ISSUE TITLE
DataObject records with `in_manifest` failing in data object construction

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#303]
```
root@scheduler-645f4d56b6-j9b5f:/conf# INFO:root:Initializing Scheduler
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/src/nmdc_automation/workflow_automation/sched.py", line 350, in <module>
    main(site_conf=sys.argv[1], wf_file=sys.argv[2])
  File "/src/nmdc_automation/workflow_automation/sched.py", line 341, in main
    sched.cycle(dryrun=dryrun, skiplist=skiplist, allowlist=allowlist)
  File "/src/nmdc_automation/workflow_automation/sched.py", line 286, in cycle
    wfp_nodes = load_workflow_process_nodes(self.db, self.workflows, allowlist)
  File "/src/nmdc_automation/workflow_automation/workflow_process.py", line 257, in load_workflow_process_nodes
    data_object_map = get_required_data_objects_map(db, workflows)
  File "/src/nmdc_automation/workflow_automation/workflow_process.py", line 30, in get_required_data_objects_map
    data_object = DataObject(**rec)
  File "/src/nmdc_automation/models/nmdc.py", line 119, in __init__
    super().__init__(**record)
  File "<string>", line 17, in __init__
  File "/usr/local/lib/python3.9/site-packages/nmdc_schema/nmdc.py", line 5577, in __post_init__
    self.in_manifest = [v if isinstance(v, ManifestId) else ManifestId(v) for v in self.in_manifest]
  File "/usr/local/lib/python3.9/site-packages/nmdc_schema/nmdc.py", line 5577, in <listcomp>
    self.in_manifest = [v if isinstance(v, ManifestId) else ManifestId(v) for v in self.in_manifest]
  File "/usr/local/lib/python3.9/site-packages/linkml_runtime/utils/metamodelcore.py", line 104, in __init__
    raise ValueError(f"{v} is not a valid URI or CURIE")
ValueError: ['nmdc:manif-11-91gc1f77'] is not a valid URI or CURIE
```

**Comment by eecavanna** [comment]
Regarding the source of this issue, @aclum is checking in about some changesheets referenced in https://github.com/microbiomedata/issues/issues/948#issuecomment-2499009932. At this point, she suspects there is an issue with changesheet validation.

**Comment by eecavanna** [comment]
I think I'll be able to fix the problematic records in the dev Mongo database by hand. I'm going to explore the database now to try to gauge the scope of the task of manually fixing them. I'll report back.

**Comment by aclum** [comment]
I just checked and  changesheet validate and linkml-validate both allow this data.

**Comment by eecavanna** [comment]
Very helpful — thanks!

Here's a link to the docs about the `in_manifest` slot (for my own future reference): 
- https://microbiomedata.github.io/nmdc-schema/in_manifest/

I'm wondering whether there is an inadequate (e.g. unintentionally lenient) structured pattern defined somewhere.

**Comment by eecavanna** [comment]
In the development database, there are currently 208 documents that exhibit this issue.

```js
db.getCollection("data_object_set").countDocuments({
    "in_manifest": {
        "$elemMatch": {
            "$regex": /^\[/
        }
    }
});

// 208
```

Those documents can be found via this query:

```js
db.getCollection("data_object_set").find({
    "in_manifest": {
        "$elemMatch": {
            "$regex": /^\[/
        }
    }
});
```

Since there are so many, I won't update them manually. FYI: @mbthornton-lbl 

I will pursue updating them programmatically (hopefully via Mongo alone, as opposed to involving Python). I will report back.

**Comment by bmeluch** [comment]
I think I can fix with changesheets if you want? Remove in_manifest records and replace them with correctly formatted ones?

**Comment by eecavanna** [comment]
Hi @bmeluch, thanks for offering. I don't think it'll be necessary. I think I'll have them fixed via a Mongo script in about 10 minutes. I'll report back then to confirm.

On a related note, is the original changesheet (which inserted the "malformed" values) something that will eventually be run in production? It sounds like our Runtime considers it to be valid (that's an issue we'll address... TBD exactly how). I would like that original changesheet to be updated to not insert "malformed" values.

**Comment by bmeluch** [comment]
@eecavanna the records are already in prod, I thought the dev response looked weird so I changed the formatting of the changesheet before submitting to prod. So hopefully prod is fine. Sorry I didn't realize the looking weird would be an actual problem!

**Comment by bmeluch** [comment]
correct me if I'm wrong @samobermiller but you said that when you were checking the changesheet, it wouldn't validate for you UNLESS you formatted it `['nmdc:manif-11-7796sg87']` right?

For me it validated both with and without brackets.
Multivalued slots in changesheets are a pain.

snippets for reference:

original changesheet that went into dev:
```
id	associated_studies	action	attribute	value
nmdc:dobj-11-nj004g50	nmdc:sty-11-aygzgv51	insert	in_manifest	['nmdc:manif-11-7796sg87']
nmdc:dobj-11-bapzh338	nmdc:sty-11-aygzgv51	insert	in_manifest	['nmdc:manif-11-7796sg87']
etc.
```

edited changesheet that went into prod:
```
id	associated_studies	action	attribute	value
nmdc:dobj-11-nj004g50	nmdc:sty-11-aygzgv51	insert	in_manifest	nmdc:manif-11-7796sg87
nmdc:dobj-11-bapzh338	nmdc:sty-11-aygzgv51	insert	in_manifest	nmdc:manif-11-7796sg87
etc.
```

**Comment by eecavanna** [comment]
#### Update

I ran the following Mongo script to update these documents.

```js
// Find documents having a problematic `in_manifest` value (and no other `in_manifest` values):
const documents = db.getCollection("data_object_set").find({
    "in_manifest": {
        "$elemMatch": {
            "$regex": /^\['nmdc:manif-/
        },
        "$size": 1
    }
});

// In each of those documents, update that `in_manifest` value.
// Note that there is a race condition here, since someone could
// change `in_manifest[0]` between the time I determine which
// documents to update, and the time I do the update.
documents.forEach(d => {
    const _id = d._id;
    const rawValue = d.in_manifest[0];  // "['nmdc:manif-11-7796sg87']"
    const processedValue = rawValue.replace(/^\['(.+)'\]$/, "$1");  // 'nmdc:manif-11-7796sg87'
    db.getCollection("data_object_set").update({ _id: _id }, { $set: { "in_manifest.0": processedValue } });
});
```

#### Result

The counting query now returns 0:

```js
db.getCollection("data_object_set").countDocuments({
    "in_manifest": {
        "$elemMatch": {
            "$regex": /^\['nmdc:manif-/
        },
        "$size": 1
    }
});
```

When I spot check the example problematic document from [this comment](https://github.com/microbiomedata/nmdc_automation/issues/303#issuecomment-2498999977) (i.e. the document whose `id` is `nmdc:dobj-11-hfjbht29`), I see the `in_manifest` value I expect now:

```json
{
    "_id" : ObjectId("66bd24a9aeff93e84e54f10b"),
    "id" : "nmdc:dobj-11-hfjbht29",
    "name" : "nmdc_dobj-11-agsd2f41_nmdc_dobj-11-8yvaz057_QC_metrics.tsv",
    "description" : "Overall statistics from MSGF+ search results filtered to ~5% FDR",
    "file_size_bytes" : NumberInt(173),
    "md5_checksum" : "299fa9e3ce6b29edc515146fdd452acd",
    "data_object_type" : "Metaproteomics Workflow Statistics",
    "url" : "https://nmdcdemo.emsl.pnnl.gov/proteomics/results/nmdc_dobj-11-agsd2f41_nmdc_dobj-11-8yvaz057_QC_metrics.tsv",
    "type" : "nmdc:DataObject",
    "in_manifest" : [
        "nmdc:manif-11-7796sg87"
    ]
}
```

**Comment by mbthornton-lbl** [comment]
I just re-ran the scheduler in the dev environment and it successfully found a new job:
```
root@scheduler-645f4d56b6-j9b5f:/conf# ./run.sh
./run.sh: line 8: kill: (243) - No such process
root@scheduler-645f4d56b6-j9b5f:/conf# INFO:root:Initializing Scheduler
INFO:root:Found 1 new jobs for nmdc:wfmgan-11-hg8af485.1
INFO:root:JOB RECORD: nmdc:c2b7c884-ab78-11ef-8298-3e652b5abb3d
``` 

And created a job_request in jobs:
```
{
    "_id" : ObjectId("6744f39ef8d82d27b2716c70"),
    "workflow" : {
        "id" : "MAGs: v1.3.12"
    },
    "id" : "nmdc:c2b7c884-ab78-11ef-8298-3e652b5abb3d",
    "created_at" : ISODate("2024-11-25T22:01:02.000+0000"),
    "config" : {
        "git_repo" : "https://github.com/microbiomedata/metaMAGs",
        "release" : "v1.3.12",
        "wdl" : "mbin_nmdc.wdl",
        "activity_id" : "nmdc:wfmag-12-h52r0792.1",
        "activity_set" : "workflow_execution_set",
        "was_informed_by" : "nmdc:omprc-13-01jx8727",
        "trigger_activity" : "nmdc:wfmgan-11-hg8af485.1",
        "iteration" : NumberInt(1),
        "input_prefix" : "nmdc_mags",
        "inputs" : {
            "proj" : "nmdc:wfmag-12-h52r0792.1",
            "contig_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgan-11-hg8af485.1/nmdc_wfmgan-11-hg8af485.1_contigs.fna",
            "sam_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgas-13-6dkenk77.1/nmdc_wfmgas-13-6dkenk77.1_pairedMapped_sorted.bam",
            "gff_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgan-11-hg8af485.1/nmdc_wfmgan-11-hg8af485.1_functional_annotation.gff",
            "proteins_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgan-11-hg8af485.1/nmdc_wfmgan-11-hg8af485.1_proteins.faa",
            "cog_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgan-11-hg8af485.1/nmdc_wfmgan-11-hg8af485.1_cog.gff",
            "ec_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgan-11-hg8af485.1/nmdc_wfmgan-11-hg8af485.1_ec.tsv",
            "ko_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgan-11-hg8af485.1/nmdc_wfmgan-11-hg8af485.1_ko.tsv",
            "pfam_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgan-11-hg8af485.1/nmdc_wfmgan-11-hg8af485.1_pfam.gff",
            "tigrfam_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgan-11-hg8af485.1/nmdc_wfmgan-11-hg8af485.1_tigrfam.gff",
            "crispr_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgan-11-hg8af485.1/nmdc_wfmgan-11-hg8af485.1_crt.crisprs",
            "product_names_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgan-11-hg8af485.1/nmdc_wfmgan-11-hg8af485.1_product_names.tsv",
            "gene_phylogeny_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgan-11-hg8af485.1/nmdc_wfmgan-11-hg8af485.1_gene_phylogeny.tsv",
            "lineage_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgan-11-hg8af485.1/nmdc_wfmgan-11-hg8af485.1_scaffold_lineage.tsv",
            "map_file" : "https://data.microbiomedata.org/data/nmdc:omprc-13-01jx8727/nmdc:wfmgan-11-hg8af485.1/nmdc_wfmgan-11-hg8af485.1_contig_names_mapping.tsv"
        },
```

**Comment by eecavanna** [comment]
> the records are already in prod, I thought the dev response looked weird so I changed the formatting of the changesheet before submitting to prod. 

Thanks for clarifying, @bmeluch!

By the way, @aclum has created a ticket about addressing the fact that `linkml-validate` considered that value to be valid. Here's a link to that ticket: https://github.com/microbiomedata/nmdc-schema/issues/2274

Closing this ticked since it was about those specific 208 records.
