### ISSUE TITLE
Fix error in `jgi_file_metadata.py`

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#76]
```
Traceback (most recent call last):
  File "/Users/MBThornton/Documents/code/nmdc_automation/nmdc_automation/jgi_file_staging/./jgi_file_metadata.py", line 320, in <module>
    get_samples_data(
  File "/Users/MBThornton/Documents/code/nmdc_automation/nmdc_automation/jgi_file_staging/./jgi_file_metadata.py", line 72, in get_samples_data
    insert_samples_into_mongodb(gold_analysis_files_df.to_dict("records"))
TypeError: insert_samples_into_mongodb() missing 1 required positional argument: 'mdb'

```

**Comment by mflynn-lanl** [comment]
`insert_samples_into_mongodb()` does not take `mdb` as an argument, it is created in the function itself

**Comment by aclum** [comment]
Closing this as obsolete, jgi_file_staging is working as far as I know.
